name: Deploy on EC2

on:
  workflow_run:
    workflows:
      - Build and Push Docker Image (Dev)
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Configurar SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Paso 2: Implementar en el servidor EC2
      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << EOF
            # Detenemos los contenedores
            sudo docker-compose -f docker-compose-back-deploy-ec2.yml down


            # Actualizamos la imagen del backedn a su ultima version.
            docker pull igrowker/i004-crewland-back-dev-image:latest


            # Ir al directorio del proyecto
            cd /home/ubuntu/crewland/i004-devops


            # Actualizar el contenido del repositorio
            git reset --hard  # Asegurarse de eliminar cambios locales no deseados
            git pull origin main  # Actualiza desde la rama main

            # Ir al directorio del docker-compose
            cd /home/ubuntu/crewland/i004-devops/crewland
                       
            sudo docker-compose -f docker-compose-back-deploy-ec2.yml up --build -d
          EOF
